packages:
  - app/*
  - lib/*

catalog:
  better-auth: 1.3.4
  typescript: ^5.9.2
  vitest: ^3.2.4
  zod: 4.0.14
  react: ^19.1.1
  react-dom: ^19.1.1
  "@types/react": ^19.1.9
  "@types/react-dom": ^19.1.7
