packages:
  - app/*
  - lib/*

catalog:
  "@tanstack/react-query": ^5.85.3
  "@types/react": 19.1.9
  "@types/react-dom": 19.1.7
  better-auth: 1.3.4
  react: 19.1.1
  react-dom: 19.1.1
  sonner: 2.0.7
  typescript: 5.9.2
  vitest: 3.2.4
  zod: 4.0.14
