# for local development and testing, not for production
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  serverless-redis-http:
    ports:
      - "8079:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: "redis://redis:6379" # Using `redis` hostname since they're in the same Docker network.
  waline:
    container_name: waline
    image: lizheming/waline:latest
    ports:
      - 8360:8360
    volumes:
      - ./data.local:/app/data
    environment:
      TZ: "Asia/Shanghai"
      SQLITE_PATH: "/app/data"
      JWT_TOKEN: "dev token"
      SITE_NAME: "Yunfi blog"
      SITE_URL: "https://yfi.moe"
      DISABLE_REGION: true
      AKISMET_KEY: false
